### ISSUE TITLE
Jest Unit Testing of the Auth Service Class

### ISSUE THREAD

**Issue by hkd987** [cedpoilly/vue-gapi#24]
https://github.com/hkd987/vue-gapi/tree/jest-testing

Working on unit testing the AuthService Class. Any help would be appreciated. 
My thought was to use JEST for this. I have already set up the structure

**Comment by nidkil** [comment]
Sorry, just saw this issue now. Mea culpa.

Yes, Jest is the way to go. I was looking at this for another project I'm working on (authenticating against Azure Active Directory using MSAL.js). It is pretty challenging to test the real OAuth flow due to the security measures that are in place to avoid bots hacking the authentication server. I have choosen to use mocks for the OAuth library and just testing the expected responses and how the code handles these. Seems like very superficial tests, but at least I now my code is responding and handling these correctly.

Do you have a feauture branch that I can look at?

**Comment by hkd987** [comment]
https://github.com/hkd987/vue-gapi/tree/jest-testing

working with @cedpoilly to mock the init gapi response. This is a solid starting point I have the auth response mocked out right now.

**Comment by cedpoilly** [comment]
Waw. I have  just tried the tests on your branch @hkd987. Seems awesome!

**Comment by hkd987** [comment]
I haven't put much work into this since Dec. Seems like we might need to find a way to test without testing the auth section.

**Comment by hkd987** [comment]
First pull reqeust of many on this issue builds the framework. 

https://github.com/cedpoilly/vue-gapi/pull/26
