### ISSUE TITLE
How to make gapi available to all component?

### ISSUE THREAD

**Issue by Tropicalista** [cedpoilly/vue-gapi#32]
I have a lot of component make use of this plugin.

How can I make gapi available to all compoentns before app starts?

At the moment I have the following code in every component:
```       
 this.$getGapiClient()
            .then(gapi => { ... })
```

**Comment by cedpoilly** [comment]
@Tropicalista I do not have a design for this yet. The reason for the syntax you've mentioned is due the the async nature of the package.
The GAPI client is returned on a promise resolution. This is so that at any moment that your code is executed, the client has been initialised with all the requested APIs.

I am open to suggestions for how the API for the package could look like. 😉
